In [1]:
pip install numpy

In [1]:
import numpy as np

In [35]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [36]:
type(arr)

numpy.ndarray

In [37]:
arr

array([1, 2, 3, 4, 5])

In [38]:
arr.shape

(5,)

In [39]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [40]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [41]:
arr.shape

(3, 5)

In [42]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [43]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [44]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [45]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [61]:
arr =np.array([1,2,3,4,5,6,7,8,9])

In [47]:
arr[3]

4

In [48]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [50]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [51]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [52]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [53]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [54]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [55]:
arr = np.arange(0,10)

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr = np.arange(0,10,step = 2)

In [58]:
arr

array([0, 2, 4, 6, 8])

In [59]:
np.linspace(1,20)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [60]:
arr

array([0, 2, 4, 6, 8])

In [62]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr[3:]=100

In [66]:
arr1 = arr

In [68]:
arr1[3:]=500

In [69]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [70]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [71]:
arr1 = arr.copy()#### copy creates another memory space for arr1 

In [73]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [74]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [75]:
### some conditions for Exploratory Data Analysis

In [76]:
val = 34

In [78]:
arr< val

array([ True, False, False, False, False, False, False, False, False])

In [79]:
arr*2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [80]:
arr/2

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. , 250. ])

In [81]:
arr%2

array([1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [82]:
arr[arr<2]

array([1])

In [85]:
arr[arr<600]

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [86]:
arr[arr<300]

array([1, 2, 3])

In [87]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [89]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.arange(0,10).reshape(2,5)

In [90]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [91]:
np.ones(4)

array([1., 1., 1., 1.])

In [92]:
np.ones(4,dtype = int)

array([1, 1, 1, 1])

In [93]:
np.ones((2,5),dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
np.random.rand(3,3)

array([[0.16889238, 0.56175163, 0.15132464],
       [0.01581687, 0.11224596, 0.68518916],
       [0.35349048, 0.22839118, 0.12860659]])

In [97]:
arr_ex = np.random.randn(4,4)

In [98]:
arr_ex

array([[-0.26682397, -0.17719119,  0.43349466, -0.46948853],
       [ 1.03319238,  0.41586315, -0.13189093,  0.11794364],
       [-1.46391623, -0.0848294 ,  1.95051767, -0.72330495],
       [-0.04731991,  0.18538855, -1.77298283,  0.16142282]])

In [99]:
np.random.randint(0,100,8)

array([43, 28, 13, 41, 15, 92, 91, 96])

In [100]:
np.random.random_sample((1,5))

array([[0.48417012, 0.79299326, 0.49427557, 0.07001332, 0.40727519]])