In [55]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [56]:
df=pd.read_csv("Advertising.csv")

In [57]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [58]:
df1=df.drop("Unnamed: 0",axis=1)

In [59]:
df1

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [60]:
x=df1.drop("Sales",axis=1)

In [61]:
x.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [62]:
df1['total_spent'] = df1['TV'] + df1['Radio'] + df1["Newspaper"]
df1.head()

TV  Radio  Newspaper  Sales  total_spent
0  230.1   37.8       69.2   22.1        337.1
1   44.5   39.3       45.1   10.4        128.9
2   17.2   45.9       69.3    9.3        132.4
3  151.5   41.3       58.5   18.5        251.3
4  180.8   10.8       58.4   12.9        250.0

In [63]:
from sklearn.linear_model import LinearRegression

In [64]:
from sklearn.preprocessing import PolynomialFeatures

In [65]:
poly_conv=PolynomialFeatures(degree=3,include_bias=False)

In [66]:
final_model=LinearRegression()

In [67]:
poly_features=poly_conv.fit_transform(x)

In [68]:
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [69]:
x.shape

(200, 3)

In [70]:
poly_features.shape

(200, 19)

In [71]:
y = df1['total_spent']
y

0      337.1
1      128.9
2      132.4
3      251.3
4      250.0
       ...  
195     55.7
196    107.2
197    192.7
198    391.8
199    249.4
Name: total_spent, Length: 200, dtype: float64

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(poly_features,y, test_size=0.33, random_state=101)

In [73]:
from sklearn.preprocessing import StandardScaler

In [74]:
scaler=StandardScaler()

In [75]:
scaler.fit(X_train)

StandardScaler()

In [76]:
scaled_X_train=scaler.transform(X_train)

In [77]:
scaled_X_test=scaler.transform(X_test)

In [78]:
X_train[0]

array([1.87800000e+02, 2.11000000e+01, 9.50000000e+00, 3.52688400e+04,
       3.96258000e+03, 1.78410000e+03, 4.45210000e+02, 2.00450000e+02,
       9.02500000e+01, 6.62348815e+06, 7.44172524e+05, 3.35053980e+05,
       8.36104380e+04, 3.76445100e+04, 1.69489500e+04, 9.39393100e+03,
       4.22949500e+03, 1.90427500e+03, 8.57375000e+02])

In [79]:
scaled_X_train

array([[ 0.455913  , -0.15469995, -0.98899258, ..., -0.60618091,
        -0.56426029, -0.5063835 ],
       [-0.84432792,  1.60997604,  0.21389931, ...,  1.27808026,
         0.25379368, -0.22928072],
       [-0.2808111 ,  0.93019813,  2.36467003, ...,  2.13064753,
         2.9262847 ,  2.91162153],
       ...,
       [ 1.07281562, -1.32199535,  0.32937694, ..., -0.70151704,
        -0.50832904, -0.16601335],
       [ 0.77504147,  0.04442691, -1.2536288 , ..., -0.6570423 ,
        -0.58737703, -0.51185147],
       [ 0.16525695,  0.56627662,  1.09922775, ...,  0.67742414,
         0.75141387,  0.50797559]])

In [80]:
from sklearn.linear_model import Ridge

In [84]:
ridge_model=Ridge(alpha=10)

In [83]:
help(Ridge)

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(alpha=1.0, *, fit_intercept=True, normalize=False, copy_X=True, max_iter=None, tol=0.001, solver='auto', random_state=None)
 |  
 |  Linear least squares with l2 regularization.
 |  
 |  Minimizes the objective function::
 |  
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |  
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Regularization strength; must be a positive float. Regul

In [85]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [86]:
test_predict=ridge_model.predict(X_test)

In [87]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [88]:
MAE=mean_absolute_error(y_test,test_predict)

In [89]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predict))

In [90]:
MAE,RMSE

(0.08100478499044358, 0.10789063128198002)